# Configuration Settings for C94-M8P device
ublox_gps_node:
  ros__parameters:
    debug: 0                    # Range 0-4 (0 means no debug statements will print)
    device: /dev/ttyACM0
    frame_id: gps
    uart1:
      baudrate: 9600
    nav_rate: 1                 # 1Hz 출력 (HPG 장치 권장값)
      
    # TMODE3 Config
    tmode3: 0                   # Survey-In Mode
    sv_in:
      reset: false               # True: disables and re-enables survey-in (resets)
                                # False: Disables survey-in only if TMODE3 is
                                # disabled
      min_dur: 0          # Survey-In Minimum Duration [s]
      acc_lim: 0.0             # Survey-In Accuracy Limit [m]

    inf:
      all: false                   # Whether to display all INF messages in console
    
    publish:
      all: true
      aid:
        hui: false
      nav:
        posecef: false
