ublox_gps_node:
  ros__parameters:
    debug: 1
    device: /dev/ttyACM0
    frame_id: gps
    uart1:
      baudrate: 9600
    
    # 로봇 이동용(Rover) 설정
    tmode3: 0      # 1에서 0으로 변경
    nav_rate: 1    # 추가 (에러 방지)

    # 신호 설정 (F9P의 성능을 다 쓰기 위해)
    gnss:
      gps: true
      glonass: true
      galileo: true
      beidou: true

    publish:
      all: true
      nav:
        posecef: false
